# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/86173/Documents/code/vivado/CPU_SPOC/CPU_SPOC.srcs/sources_1/ip/ROM_D_0/ROM_D_0.xci
# IP: The module: 'ROM_D_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86173/Documents/code/vivado/CPU_SPOC/CPU_SPOC.srcs/sources_1/ip/ROM_D_0/ROM_D_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/86173/Documents/code/vivado/CPU_SPOC/CPU_SPOC.srcs/sources_1/ip/ROM_D_0/ROM_D_0.xci
# IP: The module: 'ROM_D_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86173/Documents/code/vivado/CPU_SPOC/CPU_SPOC.srcs/sources_1/ip/ROM_D_0/ROM_D_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
